# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb9024400fae7b0cd3b229060a918bfcdde8573cc6ee49a93d65ca9fb8b1db783b08df1af12b460291af4ad74c0a779740878a030e0aad38a956b8054f6de0b8

test:
  secret_key_base: 09ff678f72b585943234c741a271076abf44e8f1bd70676d115efdf4d50b670d03d2bf4d2576ca757e41ba5392a8c72262a0e80079c2805e0743034c160f4d29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
